package com.didiElectrician.domain;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address_id
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.specific_address
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String specificAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.house_number
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String houseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.commonly_used_address
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private Integer commonlyUsedAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.longitude
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.latitude
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String latitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address_id
     *
     * @return the value of address.address_id
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address_id
     *
     * @param addressId the value for address.address_id
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setAddressId(String addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.specific_address
     *
     * @return the value of address.specific_address
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getSpecificAddress() {
        return specificAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.specific_address
     *
     * @param specificAddress the value for address.specific_address
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setSpecificAddress(String specificAddress) {
        this.specificAddress = specificAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.house_number
     *
     * @return the value of address.house_number
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getHouseNumber() {
        return houseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.house_number
     *
     * @param houseNumber the value for address.house_number
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setHouseNumber(String houseNumber) {
        this.houseNumber = houseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.commonly_used_address
     *
     * @return the value of address.commonly_used_address
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public Integer getCommonlyUsedAddress() {
        return commonlyUsedAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.commonly_used_address
     *
     * @param commonlyUsedAddress the value for address.commonly_used_address
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setCommonlyUsedAddress(Integer commonlyUsedAddress) {
        this.commonlyUsedAddress = commonlyUsedAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.longitude
     *
     * @return the value of address.longitude
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.longitude
     *
     * @param longitude the value for address.longitude
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.latitude
     *
     * @return the value of address.latitude
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.latitude
     *
     * @param latitude the value for address.latitude
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }
}