package com.didiElectrician.domain;

public class BankCard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card.bank_card_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String bankCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card.bank_name
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card.bank_secret
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String bankSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card.bank_show
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String bankShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_card.salt
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String salt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.bank_card_id
     *
     * @return the value of bank_card.bank_card_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getBankCardId() {
        return bankCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.bank_card_id
     *
     * @param bankCardId the value for bank_card.bank_card_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setBankCardId(String bankCardId) {
        this.bankCardId = bankCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.bank_name
     *
     * @return the value of bank_card.bank_name
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.bank_name
     *
     * @param bankName the value for bank_card.bank_name
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.bank_secret
     *
     * @return the value of bank_card.bank_secret
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getBankSecret() {
        return bankSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.bank_secret
     *
     * @param bankSecret the value for bank_card.bank_secret
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setBankSecret(String bankSecret) {
        this.bankSecret = bankSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.bank_show
     *
     * @return the value of bank_card.bank_show
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getBankShow() {
        return bankShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.bank_show
     *
     * @param bankShow the value for bank_card.bank_show
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setBankShow(String bankShow) {
        this.bankShow = bankShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_card.salt
     *
     * @return the value of bank_card.salt
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_card.salt
     *
     * @param salt the value for bank_card.salt
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }
}