package com.didiElectrician.domain;

public class Client {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.mobile
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.username
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.password
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.security_question
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String securityQuestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.secutity_answer
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String secutityAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.address_id
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.real_name
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.name_secret
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String nameSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.legal_person_identity_card_front
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String legalPersonIdentityCardFront;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.legal_person_identity_card_back
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String legalPersonIdentityCardBack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.legal_person_identity_card_id
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String legalPersonIdentityCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.legal_person_identity_card_secret
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String legalPersonIdentityCardSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.password_salt
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String passwordSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.name_salt
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String nameSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.person_identify_salt
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String personIdentifySalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.real_name_authentication
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private Integer realNameAuthentication;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.mobile
     *
     * @return the value of client.mobile
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.mobile
     *
     * @param mobile the value for client.mobile
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.username
     *
     * @return the value of client.username
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.username
     *
     * @param username the value for client.username
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.password
     *
     * @return the value of client.password
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.password
     *
     * @param password the value for client.password
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.security_question
     *
     * @return the value of client.security_question
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getSecurityQuestion() {
        return securityQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.security_question
     *
     * @param securityQuestion the value for client.security_question
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setSecurityQuestion(String securityQuestion) {
        this.securityQuestion = securityQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.secutity_answer
     *
     * @return the value of client.secutity_answer
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getSecutityAnswer() {
        return secutityAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.secutity_answer
     *
     * @param secutityAnswer the value for client.secutity_answer
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setSecutityAnswer(String secutityAnswer) {
        this.secutityAnswer = secutityAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.address_id
     *
     * @return the value of client.address_id
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.address_id
     *
     * @param addressId the value for client.address_id
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setAddressId(String addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.real_name
     *
     * @return the value of client.real_name
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.real_name
     *
     * @param realName the value for client.real_name
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.name_secret
     *
     * @return the value of client.name_secret
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getNameSecret() {
        return nameSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.name_secret
     *
     * @param nameSecret the value for client.name_secret
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setNameSecret(String nameSecret) {
        this.nameSecret = nameSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.legal_person_identity_card_front
     *
     * @return the value of client.legal_person_identity_card_front
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getLegalPersonIdentityCardFront() {
        return legalPersonIdentityCardFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.legal_person_identity_card_front
     *
     * @param legalPersonIdentityCardFront the value for client.legal_person_identity_card_front
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setLegalPersonIdentityCardFront(String legalPersonIdentityCardFront) {
        this.legalPersonIdentityCardFront = legalPersonIdentityCardFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.legal_person_identity_card_back
     *
     * @return the value of client.legal_person_identity_card_back
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getLegalPersonIdentityCardBack() {
        return legalPersonIdentityCardBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.legal_person_identity_card_back
     *
     * @param legalPersonIdentityCardBack the value for client.legal_person_identity_card_back
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setLegalPersonIdentityCardBack(String legalPersonIdentityCardBack) {
        this.legalPersonIdentityCardBack = legalPersonIdentityCardBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.legal_person_identity_card_id
     *
     * @return the value of client.legal_person_identity_card_id
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getLegalPersonIdentityCardId() {
        return legalPersonIdentityCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.legal_person_identity_card_id
     *
     * @param legalPersonIdentityCardId the value for client.legal_person_identity_card_id
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setLegalPersonIdentityCardId(String legalPersonIdentityCardId) {
        this.legalPersonIdentityCardId = legalPersonIdentityCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.legal_person_identity_card_secret
     *
     * @return the value of client.legal_person_identity_card_secret
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getLegalPersonIdentityCardSecret() {
        return legalPersonIdentityCardSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.legal_person_identity_card_secret
     *
     * @param legalPersonIdentityCardSecret the value for client.legal_person_identity_card_secret
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setLegalPersonIdentityCardSecret(String legalPersonIdentityCardSecret) {
        this.legalPersonIdentityCardSecret = legalPersonIdentityCardSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.password_salt
     *
     * @return the value of client.password_salt
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getPasswordSalt() {
        return passwordSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.password_salt
     *
     * @param passwordSalt the value for client.password_salt
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setPasswordSalt(String passwordSalt) {
        this.passwordSalt = passwordSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.name_salt
     *
     * @return the value of client.name_salt
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getNameSalt() {
        return nameSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.name_salt
     *
     * @param nameSalt the value for client.name_salt
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setNameSalt(String nameSalt) {
        this.nameSalt = nameSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.person_identify_salt
     *
     * @return the value of client.person_identify_salt
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getPersonIdentifySalt() {
        return personIdentifySalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.person_identify_salt
     *
     * @param personIdentifySalt the value for client.person_identify_salt
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setPersonIdentifySalt(String personIdentifySalt) {
        this.personIdentifySalt = personIdentifySalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.real_name_authentication
     *
     * @return the value of client.real_name_authentication
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public Integer getRealNameAuthentication() {
        return realNameAuthentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.real_name_authentication
     *
     * @param realNameAuthentication the value for client.real_name_authentication
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setRealNameAuthentication(Integer realNameAuthentication) {
        this.realNameAuthentication = realNameAuthentication;
    }
}