package com.didiElectrician.domain;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_id
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.titile
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String titile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.content
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.pic
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.video
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String video;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.type
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_id
     *
     * @return the value of course.course_id
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_id
     *
     * @param courseId the value for course.course_id
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.titile
     *
     * @return the value of course.titile
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getTitile() {
        return titile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.titile
     *
     * @param titile the value for course.titile
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setTitile(String titile) {
        this.titile = titile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.content
     *
     * @return the value of course.content
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.content
     *
     * @param content the value for course.content
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.pic
     *
     * @return the value of course.pic
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.pic
     *
     * @param pic the value for course.pic
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.video
     *
     * @return the value of course.video
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.video
     *
     * @param video the value for course.video
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setVideo(String video) {
        this.video = video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.type
     *
     * @return the value of course.type
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.type
     *
     * @param type the value for course.type
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }
}