package com.didiElectrician.domain;

public class Electrician {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.mobile
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.username
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.password
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.security_question
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String securityQuestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.security_answer
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String securityAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.address_id
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.real_name
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.name_secret
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String nameSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.legal_person_identity_card_front
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String legalPersonIdentityCardFront;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.legal_person_identity_card_back
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String legalPersonIdentityCardBack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.legal_person_identity_card_id
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String legalPersonIdentityCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.legal_person_identity_card_secret
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String legalPersonIdentityCardSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.password_salt
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String passwordSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.name_salt
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String nameSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.person_identify_salt
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String personIdentifySalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.business_license
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private String businessLicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.type
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.real_name_authentication
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private Integer realNameAuthentication;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column electrician.work_hour
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    private Integer workHour;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.mobile
     *
     * @return the value of electrician.mobile
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.mobile
     *
     * @param mobile the value for electrician.mobile
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.username
     *
     * @return the value of electrician.username
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.username
     *
     * @param username the value for electrician.username
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.password
     *
     * @return the value of electrician.password
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.password
     *
     * @param password the value for electrician.password
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.security_question
     *
     * @return the value of electrician.security_question
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getSecurityQuestion() {
        return securityQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.security_question
     *
     * @param securityQuestion the value for electrician.security_question
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setSecurityQuestion(String securityQuestion) {
        this.securityQuestion = securityQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.security_answer
     *
     * @return the value of electrician.security_answer
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getSecurityAnswer() {
        return securityAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.security_answer
     *
     * @param securityAnswer the value for electrician.security_answer
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setSecurityAnswer(String securityAnswer) {
        this.securityAnswer = securityAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.address_id
     *
     * @return the value of electrician.address_id
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.address_id
     *
     * @param addressId the value for electrician.address_id
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setAddressId(String addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.real_name
     *
     * @return the value of electrician.real_name
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.real_name
     *
     * @param realName the value for electrician.real_name
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.name_secret
     *
     * @return the value of electrician.name_secret
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getNameSecret() {
        return nameSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.name_secret
     *
     * @param nameSecret the value for electrician.name_secret
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setNameSecret(String nameSecret) {
        this.nameSecret = nameSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.legal_person_identity_card_front
     *
     * @return the value of electrician.legal_person_identity_card_front
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getLegalPersonIdentityCardFront() {
        return legalPersonIdentityCardFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.legal_person_identity_card_front
     *
     * @param legalPersonIdentityCardFront the value for electrician.legal_person_identity_card_front
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setLegalPersonIdentityCardFront(String legalPersonIdentityCardFront) {
        this.legalPersonIdentityCardFront = legalPersonIdentityCardFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.legal_person_identity_card_back
     *
     * @return the value of electrician.legal_person_identity_card_back
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getLegalPersonIdentityCardBack() {
        return legalPersonIdentityCardBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.legal_person_identity_card_back
     *
     * @param legalPersonIdentityCardBack the value for electrician.legal_person_identity_card_back
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setLegalPersonIdentityCardBack(String legalPersonIdentityCardBack) {
        this.legalPersonIdentityCardBack = legalPersonIdentityCardBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.legal_person_identity_card_id
     *
     * @return the value of electrician.legal_person_identity_card_id
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getLegalPersonIdentityCardId() {
        return legalPersonIdentityCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.legal_person_identity_card_id
     *
     * @param legalPersonIdentityCardId the value for electrician.legal_person_identity_card_id
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setLegalPersonIdentityCardId(String legalPersonIdentityCardId) {
        this.legalPersonIdentityCardId = legalPersonIdentityCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.legal_person_identity_card_secret
     *
     * @return the value of electrician.legal_person_identity_card_secret
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getLegalPersonIdentityCardSecret() {
        return legalPersonIdentityCardSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.legal_person_identity_card_secret
     *
     * @param legalPersonIdentityCardSecret the value for electrician.legal_person_identity_card_secret
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setLegalPersonIdentityCardSecret(String legalPersonIdentityCardSecret) {
        this.legalPersonIdentityCardSecret = legalPersonIdentityCardSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.password_salt
     *
     * @return the value of electrician.password_salt
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getPasswordSalt() {
        return passwordSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.password_salt
     *
     * @param passwordSalt the value for electrician.password_salt
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setPasswordSalt(String passwordSalt) {
        this.passwordSalt = passwordSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.name_salt
     *
     * @return the value of electrician.name_salt
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getNameSalt() {
        return nameSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.name_salt
     *
     * @param nameSalt the value for electrician.name_salt
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setNameSalt(String nameSalt) {
        this.nameSalt = nameSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.person_identify_salt
     *
     * @return the value of electrician.person_identify_salt
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getPersonIdentifySalt() {
        return personIdentifySalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.person_identify_salt
     *
     * @param personIdentifySalt the value for electrician.person_identify_salt
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setPersonIdentifySalt(String personIdentifySalt) {
        this.personIdentifySalt = personIdentifySalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.business_license
     *
     * @return the value of electrician.business_license
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public String getBusinessLicense() {
        return businessLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.business_license
     *
     * @param businessLicense the value for electrician.business_license
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setBusinessLicense(String businessLicense) {
        this.businessLicense = businessLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.type
     *
     * @return the value of electrician.type
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.type
     *
     * @param type the value for electrician.type
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.real_name_authentication
     *
     * @return the value of electrician.real_name_authentication
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public Integer getRealNameAuthentication() {
        return realNameAuthentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.real_name_authentication
     *
     * @param realNameAuthentication the value for electrician.real_name_authentication
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setRealNameAuthentication(Integer realNameAuthentication) {
        this.realNameAuthentication = realNameAuthentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column electrician.work_hour
     *
     * @return the value of electrician.work_hour
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public Integer getWorkHour() {
        return workHour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column electrician.work_hour
     *
     * @param workHour the value for electrician.work_hour
     *
     * @mbggenerated Sun Apr 08 18:51:19 CST 2018
     */
    public void setWorkHour(Integer workHour) {
        this.workHour = workHour;
    }
}