package com.didiElectrician.domain;

public class EWallet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_wallet.e_wallet_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String eWalletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_wallet.balance
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private Double balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_wallet.user_mobile
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String userMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_wallet.type
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_wallet.visible
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private Byte visible;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_wallet.e_wallet_id
     *
     * @return the value of e_wallet.e_wallet_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String geteWalletId() {
        return eWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_wallet.e_wallet_id
     *
     * @param eWalletId the value for e_wallet.e_wallet_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void seteWalletId(String eWalletId) {
        this.eWalletId = eWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_wallet.balance
     *
     * @return the value of e_wallet.balance
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_wallet.balance
     *
     * @param balance the value for e_wallet.balance
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_wallet.user_mobile
     *
     * @return the value of e_wallet.user_mobile
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_wallet.user_mobile
     *
     * @param userMobile the value for e_wallet.user_mobile
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_wallet.type
     *
     * @return the value of e_wallet.type
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_wallet.type
     *
     * @param type the value for e_wallet.type
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_wallet.visible
     *
     * @return the value of e_wallet.visible
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public Byte getVisible() {
        return visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_wallet.visible
     *
     * @param visible the value for e_wallet.visible
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setVisible(Byte visible) {
        this.visible = visible;
    }
}