package com.didiElectrician.domain;

public class Feedback {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.feedback_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String feedbackId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.description
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.remark
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.pic
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.video
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String video;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.work_order_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String workOrderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.feedback_id
     *
     * @return the value of feedback.feedback_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getFeedbackId() {
        return feedbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.feedback_id
     *
     * @param feedbackId the value for feedback.feedback_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setFeedbackId(String feedbackId) {
        this.feedbackId = feedbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.description
     *
     * @return the value of feedback.description
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.description
     *
     * @param description the value for feedback.description
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.remark
     *
     * @return the value of feedback.remark
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.remark
     *
     * @param remark the value for feedback.remark
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.pic
     *
     * @return the value of feedback.pic
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.pic
     *
     * @param pic the value for feedback.pic
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.video
     *
     * @return the value of feedback.video
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.video
     *
     * @param video the value for feedback.video
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setVideo(String video) {
        this.video = video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.work_order_id
     *
     * @return the value of feedback.work_order_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getWorkOrderId() {
        return workOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.work_order_id
     *
     * @param workOrderId the value for feedback.work_order_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setWorkOrderId(String workOrderId) {
        this.workOrderId = workOrderId;
    }
}