package com.didiElectrician.domain;

public class Permission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_id
     *
     * @mbggenerated Sun Apr 08 18:55:17 CST 2018
     */
    private String permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.description
     *
     * @mbggenerated Sun Apr 08 18:55:17 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission
     *
     * @mbggenerated Sun Apr 08 18:55:17 CST 2018
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.icon
     *
     * @mbggenerated Sun Apr 08 18:55:17 CST 2018
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.module_id
     *
     * @mbggenerated Sun Apr 08 18:55:17 CST 2018
     */
    private String moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.available
     *
     * @mbggenerated Sun Apr 08 18:55:17 CST 2018
     */
    private Integer available;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_id
     *
     * @return the value of permission.permission_id
     *
     * @mbggenerated Sun Apr 08 18:55:17 CST 2018
     */
    public String getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_id
     *
     * @param permissionId the value for permission.permission_id
     *
     * @mbggenerated Sun Apr 08 18:55:17 CST 2018
     */
    public void setPermissionId(String permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.description
     *
     * @return the value of permission.description
     *
     * @mbggenerated Sun Apr 08 18:55:17 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.description
     *
     * @param description the value for permission.description
     *
     * @mbggenerated Sun Apr 08 18:55:17 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission
     *
     * @return the value of permission.permission
     *
     * @mbggenerated Sun Apr 08 18:55:17 CST 2018
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission
     *
     * @param permission the value for permission.permission
     *
     * @mbggenerated Sun Apr 08 18:55:17 CST 2018
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.icon
     *
     * @return the value of permission.icon
     *
     * @mbggenerated Sun Apr 08 18:55:17 CST 2018
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.icon
     *
     * @param icon the value for permission.icon
     *
     * @mbggenerated Sun Apr 08 18:55:17 CST 2018
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.module_id
     *
     * @return the value of permission.module_id
     *
     * @mbggenerated Sun Apr 08 18:55:17 CST 2018
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.module_id
     *
     * @param moduleId the value for permission.module_id
     *
     * @mbggenerated Sun Apr 08 18:55:17 CST 2018
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.available
     *
     * @return the value of permission.available
     *
     * @mbggenerated Sun Apr 08 18:55:17 CST 2018
     */
    public Integer getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.available
     *
     * @param available the value for permission.available
     *
     * @mbggenerated Sun Apr 08 18:55:17 CST 2018
     */
    public void setAvailable(Integer available) {
        this.available = available;
    }
}