package com.didiElectrician.domain;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_description
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String roleDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_text
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String roleText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_id
     *
     * @return the value of role.role_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_id
     *
     * @param roleId the value for role.role_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_description
     *
     * @return the value of role.role_description
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getRoleDescription() {
        return roleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_description
     *
     * @param roleDescription the value for role.role_description
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_text
     *
     * @return the value of role.role_text
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getRoleText() {
        return roleText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_text
     *
     * @param roleText the value for role.role_text
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setRoleText(String roleText) {
        this.roleText = roleText;
    }
}