package com.didiElectrician.domain;

public class RoleModule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_module.role_module_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String roleModuleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_module.role_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_module.module_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String moduleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_module.role_module_id
     *
     * @return the value of role_module.role_module_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getRoleModuleId() {
        return roleModuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_module.role_module_id
     *
     * @param roleModuleId the value for role_module.role_module_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setRoleModuleId(String roleModuleId) {
        this.roleModuleId = roleModuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_module.role_id
     *
     * @return the value of role_module.role_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_module.role_id
     *
     * @param roleId the value for role_module.role_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_module.module_id
     *
     * @return the value of role_module.module_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_module.module_id
     *
     * @param moduleId the value for role_module.module_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId;
    }
}