package com.didiElectrician.domain;

import java.util.Date;

public class TransactionRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_record.transaction_record_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String transactionRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_record.transaction_time
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private Date transactionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_record.transaction_description
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String transactionDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_record.transaction_way
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private Integer transactionWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_record.reconciliation
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private Integer reconciliation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_record.e_wallet_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String eWalletId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_record.transaction_record_id
     *
     * @return the value of transaction_record.transaction_record_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getTransactionRecordId() {
        return transactionRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_record.transaction_record_id
     *
     * @param transactionRecordId the value for transaction_record.transaction_record_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setTransactionRecordId(String transactionRecordId) {
        this.transactionRecordId = transactionRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_record.transaction_time
     *
     * @return the value of transaction_record.transaction_time
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public Date getTransactionTime() {
        return transactionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_record.transaction_time
     *
     * @param transactionTime the value for transaction_record.transaction_time
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setTransactionTime(Date transactionTime) {
        this.transactionTime = transactionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_record.transaction_description
     *
     * @return the value of transaction_record.transaction_description
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getTransactionDescription() {
        return transactionDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_record.transaction_description
     *
     * @param transactionDescription the value for transaction_record.transaction_description
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setTransactionDescription(String transactionDescription) {
        this.transactionDescription = transactionDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_record.transaction_way
     *
     * @return the value of transaction_record.transaction_way
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public Integer getTransactionWay() {
        return transactionWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_record.transaction_way
     *
     * @param transactionWay the value for transaction_record.transaction_way
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setTransactionWay(Integer transactionWay) {
        this.transactionWay = transactionWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_record.reconciliation
     *
     * @return the value of transaction_record.reconciliation
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public Integer getReconciliation() {
        return reconciliation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_record.reconciliation
     *
     * @param reconciliation the value for transaction_record.reconciliation
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setReconciliation(Integer reconciliation) {
        this.reconciliation = reconciliation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_record.e_wallet_id
     *
     * @return the value of transaction_record.e_wallet_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String geteWalletId() {
        return eWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_record.e_wallet_id
     *
     * @param eWalletId the value for transaction_record.e_wallet_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void seteWalletId(String eWalletId) {
        this.eWalletId = eWalletId;
    }
}