package com.didiElectrician.domain;

import java.util.Date;

public class WalletChangeLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_change_log.wallet_change_log_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String walletChangeLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_change_log.change_status
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private Byte changeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_change_log.change_time
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private Date changeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_change_log.change_money
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private Double changeMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_change_log.check
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private Byte check;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wallet_change_log.e_wallet_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String eWalletId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_change_log.wallet_change_log_id
     *
     * @return the value of wallet_change_log.wallet_change_log_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getWalletChangeLogId() {
        return walletChangeLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_change_log.wallet_change_log_id
     *
     * @param walletChangeLogId the value for wallet_change_log.wallet_change_log_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setWalletChangeLogId(String walletChangeLogId) {
        this.walletChangeLogId = walletChangeLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_change_log.change_status
     *
     * @return the value of wallet_change_log.change_status
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public Byte getChangeStatus() {
        return changeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_change_log.change_status
     *
     * @param changeStatus the value for wallet_change_log.change_status
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setChangeStatus(Byte changeStatus) {
        this.changeStatus = changeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_change_log.change_time
     *
     * @return the value of wallet_change_log.change_time
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public Date getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_change_log.change_time
     *
     * @param changeTime the value for wallet_change_log.change_time
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_change_log.change_money
     *
     * @return the value of wallet_change_log.change_money
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public Double getChangeMoney() {
        return changeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_change_log.change_money
     *
     * @param changeMoney the value for wallet_change_log.change_money
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setChangeMoney(Double changeMoney) {
        this.changeMoney = changeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_change_log.check
     *
     * @return the value of wallet_change_log.check
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public Byte getCheck() {
        return check;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_change_log.check
     *
     * @param check the value for wallet_change_log.check
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setCheck(Byte check) {
        this.check = check;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wallet_change_log.e_wallet_id
     *
     * @return the value of wallet_change_log.e_wallet_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String geteWalletId() {
        return eWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wallet_change_log.e_wallet_id
     *
     * @param eWalletId the value for wallet_change_log.e_wallet_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void seteWalletId(String eWalletId) {
        this.eWalletId = eWalletId;
    }
}