package com.didiElectrician.domain;

import java.util.Date;

public class WorkOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.work_order_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String workOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.address
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.longitude
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.latitudu
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String latitudu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.titile
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String titile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.description
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.picture_url
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String pictureUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.video_url
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String videoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.create_time
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.after_sale_time
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private Date afterSaleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.update_time
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.over_time
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private Date overTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.client_mobile
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String clientMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_order.electrician_mobile
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    private String electricianMobile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.work_order_id
     *
     * @return the value of work_order.work_order_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getWorkOrderId() {
        return workOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.work_order_id
     *
     * @param workOrderId the value for work_order.work_order_id
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setWorkOrderId(String workOrderId) {
        this.workOrderId = workOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.address
     *
     * @return the value of work_order.address
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.address
     *
     * @param address the value for work_order.address
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.longitude
     *
     * @return the value of work_order.longitude
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.longitude
     *
     * @param longitude the value for work_order.longitude
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.latitudu
     *
     * @return the value of work_order.latitudu
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getLatitudu() {
        return latitudu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.latitudu
     *
     * @param latitudu the value for work_order.latitudu
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setLatitudu(String latitudu) {
        this.latitudu = latitudu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.titile
     *
     * @return the value of work_order.titile
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getTitile() {
        return titile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.titile
     *
     * @param titile the value for work_order.titile
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setTitile(String titile) {
        this.titile = titile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.description
     *
     * @return the value of work_order.description
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.description
     *
     * @param description the value for work_order.description
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.picture_url
     *
     * @return the value of work_order.picture_url
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.picture_url
     *
     * @param pictureUrl the value for work_order.picture_url
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.video_url
     *
     * @return the value of work_order.video_url
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.video_url
     *
     * @param videoUrl the value for work_order.video_url
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.create_time
     *
     * @return the value of work_order.create_time
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.create_time
     *
     * @param createTime the value for work_order.create_time
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.after_sale_time
     *
     * @return the value of work_order.after_sale_time
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public Date getAfterSaleTime() {
        return afterSaleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.after_sale_time
     *
     * @param afterSaleTime the value for work_order.after_sale_time
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setAfterSaleTime(Date afterSaleTime) {
        this.afterSaleTime = afterSaleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.update_time
     *
     * @return the value of work_order.update_time
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.update_time
     *
     * @param updateTime the value for work_order.update_time
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.over_time
     *
     * @return the value of work_order.over_time
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public Date getOverTime() {
        return overTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.over_time
     *
     * @param overTime the value for work_order.over_time
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setOverTime(Date overTime) {
        this.overTime = overTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.client_mobile
     *
     * @return the value of work_order.client_mobile
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getClientMobile() {
        return clientMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.client_mobile
     *
     * @param clientMobile the value for work_order.client_mobile
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setClientMobile(String clientMobile) {
        this.clientMobile = clientMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_order.electrician_mobile
     *
     * @return the value of work_order.electrician_mobile
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public String getElectricianMobile() {
        return electricianMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_order.electrician_mobile
     *
     * @param electricianMobile the value for work_order.electrician_mobile
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    public void setElectricianMobile(String electricianMobile) {
        this.electricianMobile = electricianMobile;
    }
}