package com.didiElectrician.dao;

import com.didiElectrician.dao.base.SinglePrimaryKeyBaseMapper;
import com.didiElectrician.domain.BankCard;

public interface BankCardMapper extends SinglePrimaryKeyBaseMapper<BankCard> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_card
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int deleteByPrimaryKey(String bankCardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_card
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int insert(BankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_card
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int insertSelective(BankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_card
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    BankCard selectByPrimaryKey(String bankCardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_card
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int updateByPrimaryKeySelective(BankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_card
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int updateByPrimaryKey(BankCard record);
}