package com.didiElectrician.dao;

import com.didiElectrician.domain.Client;

public interface ClientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int deleteByPrimaryKey(String mobile);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int insert(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int insertSelective(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    Client selectByPrimaryKey(String mobile);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int updateByPrimaryKeySelective(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int updateByPrimaryKey(Client record);
}