package com.didiElectrician.dao;

import com.didiElectrician.domain.Electrician;

public interface ElectricianMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electrician
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int deleteByPrimaryKey(String mobile);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electrician
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int insert(Electrician record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electrician
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int insertSelective(Electrician record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electrician
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    Electrician selectByPrimaryKey(String mobile);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electrician
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int updateByPrimaryKeySelective(Electrician record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table electrician
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int updateByPrimaryKey(Electrician record);
}