package com.didiElectrician.dao;

import com.didiElectrician.dao.base.SinglePrimaryKeyBaseMapper;
import com.didiElectrician.domain.EWallet;

public interface EWalletMapper extends SinglePrimaryKeyBaseMapper<EWallet> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_wallet
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int deleteByPrimaryKey(String eWalletId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_wallet
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int insert(EWallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_wallet
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int insertSelective(EWallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_wallet
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    EWallet selectByPrimaryKey(String eWalletId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_wallet
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int updateByPrimaryKeySelective(EWallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_wallet
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int updateByPrimaryKey(EWallet record);
}