package com.didiElectrician.dao;

import com.didiElectrician.dao.base.SinglePrimaryKeyBaseMapper;
import com.didiElectrician.domain.WorkOrderStatus;

public interface WorkOrderStatusMapper extends SinglePrimaryKeyBaseMapper<WorkOrderStatus> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_status
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int deleteByPrimaryKey(String workOrderStatusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_status
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int insert(WorkOrderStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_status
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int insertSelective(WorkOrderStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_status
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    WorkOrderStatus selectByPrimaryKey(String workOrderStatusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_status
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int updateByPrimaryKeySelective(WorkOrderStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_order_status
     *
     * @mbggenerated Mon Apr 02 19:50:50 CST 2018
     */
    int updateByPrimaryKey(WorkOrderStatus record);
}